name: Binary Packages

on:
  release:
    types:
      - created

jobs:
  amd64-gnu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deduce release
        id: release_info
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y cpanminus curl gcc make
          cpanm -v ExtUtils::Command Pod::Usage

      - name: System Information
        run: ./bin/rstar sysinfo

      - name: Fetch
        run: ./bin/rstar fetch

      - name: Install
        env:
          RSTAR_DEBUG: "1"
        run: ./bin/rstar install -p "/tmp/ci-$GITHUB_RUN_ID"

      - name: Package
        run: |
          cd -- "/tmp/ci-$GITHUB_RUN_ID"
          tar -c \
            --mtime "@$(git -C "$GITHUB_WORKSPACE" log -1 --pretty=format:%at)" \
            --mode=go=rX,u+rw,a-s \
            --format=gnu \
            --numeric-owner --owner=0 --group=0 \
            . \
            | gzip -9cn \
            > "/tmp/dist.tar.gz"

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release_info.outputs.upload_url }}
          asset_path: /tmp/dist.tar.gz
          asset_name: rakudo-star-amd64-gnu-${{ steps.release_info.outputs.name }}.tar.gz
          asset_content_type: application/gzip
