name: Prerelease

on:
  push:
    tags:
      - '*-rc*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_USER: ${{ secrets.WORKFLOW_RELEASE_USER }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_RELEASE_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            This is a release candidate of Rakudo Star. It is ment for testing
            purposes, to eventually release a production quality release.
          draft: false
          prerelease: true
