# This is a basic workflow to help you get started with Actions

name: Build Rakudo Star for Windows

# Triggers the workflow on new tag's or branches
on: [create, workflow_dispatch]
#  [push, create, workflow_dispatch]
jobs:
  # This workflow contains a single job called "build ..."
  build Rakudo-Star Windows MSI package:
    # Windows-latest has almost all requirements to build rakudo-star-win
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v3
      - name: Run the build-with-choco.ps1 script
        run: pwsh -command ".\$GITHUB_WORKSPACE\tools\build\binary-release\build-with-choco.ps1"
      - name: Upload output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Upload output directory
          path: tools/build/binary-release/Windows/
          if-no-files-found: error
      - name: Release Rakudo-Star Windows MSI package
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "tools/build/binary-release/Windows/*"
          token: ${{ secrets.GITHUB_TOKEN }}
