name: Release

on:
  push: workflow_dispatch
#    tags:
#      - '*'
#      - '!*-rc*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            This is release ${{ github.ref }} of Rakudo Star.
          draft: false
          prerelease: false
